let invoiceItems=[];
const fmt=n=>'₹'+Number(n||0).toFixed(2);
const byId=id=>document.getElementById(id);
async function refresh(){
 const products=await getAll('products'), invoices=await getAll('invoices'), accounts=await getAll('accounts'), journals=await getAll('journals');
 byId('productCount').textContent=products.length; byId('invoiceCount').textContent=invoices.length;
 byId('salesTotal').textContent=fmt(invoices.reduce((s,i)=>s+i.total,0));
 byId('productTable').innerHTML=products.map(p=>`<tr><td>${p.name}</td><td>${fmt(p.price)}</td><td>${p.qty}</td><td><button class="danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join('');
 byId('saleProduct').innerHTML='<option value="">Select Product</option>'+products.map(p=>`<option value="${p.id}">${p.name} (Stock: ${p.qty})</option>`).join('');
 const options='<option value="">Select Account</option>'+accounts.map(a=>`<option value="${a.id}">${a.name} (${a.type})</option>`).join('');
 byId('debitAccount').innerHTML=options;byId('creditAccount').innerHTML=options;
 byId('accountTable').innerHTML=accounts.map(a=>`<tr><td>${a.name}</td><td>${a.type}</td></tr>`).join('');
 byId('journalTable').innerHTML=journals.map(j=>`<tr><td>${j.date}</td><td>${j.debitName}</td><td>${j.creditName}</td><td>${fmt(j.amount)}</td><td>${j.narration||''}</td></tr>`).join('');
 byId('salesTable').innerHTML=invoices.map(i=>`<tr><td>${i.id}</td><td>${i.date}</td><td>${i.customer||'Cash Customer'}</td><td>${fmt(i.total)}</td><td><button onclick="printInvoice(${i.id})">Print</button></td></tr>`).join('');
 renderInvoice();
}
byId('productForm').onsubmit=async e=>{e.preventDefault();await add('products',{name:byId('pname').value,price:+byId('pprice').value,qty:+byId('pqty').value});e.target.reset();refresh()};
async function deleteProduct(id){if(confirm('Delete product?')){await remove('products',id);refresh()}}
byId('addItem').onclick=async()=>{const id=+byId('saleProduct').value,qty=+byId('saleQty').value;if(!id||qty<=0)return;const p=(await getAll('products')).find(x=>x.id===id);if(!p||p.qty<qty)return alert('Insufficient Quantity');const old=invoiceItems.find(x=>x.id===id);if(old)old.qty+=qty;else invoiceItems.push({...p,qty});renderInvoice()};
function renderInvoice(){byId('invoiceItems').innerHTML=invoiceItems.map((x,n)=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${fmt(x.price)}</td><td>${fmt(x.qty*x.price)}</td><td><button onclick="invoiceItems.splice(${n},1);renderInvoice()">X</button></td></tr>`).join('');byId('invoiceTotal').textContent=fmt(invoiceItems.reduce((s,x)=>s+x.qty*x.price,0))}
byId('finalizeInvoice').onclick=async()=>{if(!invoiceItems.length)return alert('Add products first');const products=await getAll('products');for(const x of invoiceItems){const p=products.find(a=>a.id===x.id);if(p.qty<x.qty)return alert('Insufficient Quantity for '+p.name);p.qty-=x.qty;await put('products',p)}const total=invoiceItems.reduce((s,x)=>s+x.qty*x.price,0);const id=await add('invoices',{date:new Date().toLocaleString(),customer:byId('customerName').value,items:invoiceItems,total});invoiceItems=[];byId('customerName').value='';await refresh();printInvoice(id)};
async function printInvoice(id){const i=(await getAll('invoices')).find(x=>x.id===id);if(!i)return;const html=`<div class="report-box"><h2 class="report-title">TAX INVOICE</h2><p><b>Invoice No:</b> ${i.id}<br><b>Date:</b> ${i.date}<br><b>Customer:</b> ${i.customer||'Cash Customer'}</p><table><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${i.items.map(x=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${fmt(x.price)}</td><td>${fmt(x.qty*x.price)}</td></tr>`).join('')}</table><h3 style="text-align:right">Grand Total: ${fmt(i.total)}</h3><p>Thank You!</p></div>`;const w=window.open('','PRINT','height=700,width=900');w.document.write(`<html><head><title>Invoice</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #000;padding:8px}</style></head><body>${html}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
byId('accountForm').onsubmit=async e=>{e.preventDefault();await add('accounts',{name:byId('accountName').value,type:byId('accountType').value});e.target.reset();refresh()};
byId('journalForm').onsubmit=async e=>{e.preventDefault();const accounts=await getAll('accounts');const d=accounts.find(a=>a.id===+byId('debitAccount').value),c=accounts.find(a=>a.id===+byId('creditAccount').value);if(!d||!c||d.id===c.id)return alert('Select different debit and credit accounts');await add('journals',{date:byId('journalDate').value,debit:d.id,credit:c.id,debitName:d.name,creditName:c.name,amount:+byId('journalAmount').value,narration:byId('journalNarration').value});e.target.reset();refresh()};
window.showReport=async type=>{const accounts=await getAll('accounts'), journals=await getAll('journals');const bal={};accounts.forEach(a=>bal[a.id]={...a,debit:0,credit:0});journals.forEach(j=>{bal[j.debit].debit+=j.amount;bal[j.credit].credit+=j.amount});let title='Trial Balance', rows=[];if(type==='trial')rows=Object.values(bal);else if(type==='pl'){title='Profit & Loss Account';rows=Object.values(bal).filter(a=>['Income','Expense'].includes(a.type))}else{title='Balance Sheet';rows=Object.values(bal).filter(a=>['Asset','Liability','Capital'].includes(a.type))}byId('reportOutput').innerHTML=`<div class="report-box"><h2 class="report-title">${title}</h2><p>Generated: ${new Date().toLocaleString()}</p><table><tr><th>Account</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr>${rows.map(a=>{let b=a.debit-a.credit;return `<tr><td>${a.name}</td><td>${a.type}</td><td>${fmt(a.debit)}</td><td>${fmt(a.credit)}</td><td>${fmt(Math.abs(b))} ${b>=0?'Dr':'Cr'}</td></tr>`}).join('')}</table></div>`};
byId('exportData').onclick=async()=>{const data={products:await getAll('products'),invoices:await getAll('invoices'),accounts:await getAll('accounts'),journals:await getAll('journals')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='pos-accounting-backup.json';a.click()};
byId('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const data=JSON.parse(r.result);for(const s of ['products','invoices','accounts','journals']){await clearStore(s);for(const item of (data[s]||[]))await put(s,item)}await refresh();alert('Backup restored')}catch(err){alert('Invalid backup file')}};r.readAsText(f)};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));byId(b.dataset.page).classList.add('active');byId('pageTitle').textContent=b.textContent});
byId('printPage').onclick=()=>window.print();
openDB().then(refresh);
